spring:
  application:
    name: AuthSystem

  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: 45678432

  jpa:
    hibernate:
      ddl-auto: create-drop


security:
  jwt:
    secret: hxiweiydbrc387y3tyrv873tbrty8732nxy9ry239xer923
    expiration: 120000

